# This workflow will verify that all pull requests have at least
# one of these labels: 'bug', 'enhancement', 'interface-change'
# before they can be merged

name: verify-pr-label-action

on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify_pr_labels:
    runs-on: ubuntu-latest
    name: Verify that the PR has a valid label
    steps:
    - name: Verify Pull Request Labels
      uses: jesusvasquez333/verify-pr-label-action@v1.3.1
      id: verify-pr-label
      with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, interface-change'
          pull-request-number: '${{ github.event.pull_request.number }}'
